const FALLBACK_RENDER_URL = "https://<your-render-url>";

export const SMART_ANALYZER_API_URL =
  process.env.NEXT_PUBLIC_SMART_ANALYZER_API_URL ?? FALLBACK_RENDER_URL;

export const PDF_INTELLIGENCE_DEMO_URL =
  process.env.NEXT_PUBLIC_PDF_INTELLIGENCE_DEMO_URL ?? FALLBACK_RENDER_URL;

export const RESUME_ANALYZER_DEMO_URL =
  process.env.NEXT_PUBLIC_RESUME_ANALYZER_DEMO_URL ?? FALLBACK_RENDER_URL;
